//! # prax-typegen
//!
//! Generate TypeScript interfaces and Zod schemas from Prax ORM schema files.
//!
//! This crate reads `.prax` schema files and produces TypeScript output that
//! mirrors the models, enums, and composite types defined in the schema.
//!
//! ## Generator Block
//!
//! Add a generator block to your `.prax` schema:
//!
//! ```prax
//! generator typescript {
//!   provider = "prax-typegen"
//!   output   = "./src/types"
//!   generate = env("TYPESCRIPT_GENERATE")
//! }
//! ```
//!
//! When `TYPESCRIPT_GENERATE` is set to `true`, `1`, or `yes` in the
//! environment, `prax generate` will invoke this generator.

mod error;
mod mapping;
mod typescript;
mod zod;

pub use error::TypegenError;
pub use mapping::TypeMapper;
pub use typescript::InterfaceGenerator;
pub use zod::ZodGenerator;

use std::path::Path;

use prax_schema::{Schema, validate_schema};

/// Result type for typegen operations.
pub type Result<T> = std::result::Result<T, TypegenError>;

/// Top-level generator that produces both interfaces and Zod schemas.
pub struct Typegen {
    pub interfaces: bool,
    pub zod: bool,
}

impl Default for Typegen {
    fn default() -> Self {
        Self {
            interfaces: true,
            zod: true,
        }
    }
}

impl Typegen {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn interfaces_only() -> Self {
        Self {
            interfaces: true,
            zod: false,
        }
    }

    pub fn zod_only() -> Self {
        Self {
            interfaces: false,
            zod: true,
        }
    }

    /// Parse a `.prax` schema file and generate TypeScript output.
    pub fn generate_from_file(&self, schema_path: &Path) -> Result<GeneratedOutput> {
        let input = std::fs::read_to_string(schema_path).map_err(|e| {
            TypegenError::Io(format!("failed to read {}: {e}", schema_path.display()))
        })?;
        self.generate_from_str(&input)
    }

    /// Generate TypeScript output from a schema string.
    pub fn generate_from_str(&self, input: &str) -> Result<GeneratedOutput> {
        let schema = validate_schema(input).map_err(|e| TypegenError::Schema(e.to_string()))?;
        self.generate(&schema)
    }

    /// Generate TypeScript output from a parsed schema.
    pub fn generate(&self, schema: &Schema) -> Result<GeneratedOutput> {
        let mut output = GeneratedOutput::default();

        if self.interfaces {
            output.interfaces = InterfaceGenerator::generate(schema);
        }
        if self.zod {
            output.zod = ZodGenerator::generate(schema);
        }

        Ok(output)
    }

    /// Generate and write files to the output directory.
    pub fn write_to_dir(&self, schema: &Schema, out_dir: &Path) -> Result<Vec<String>> {
        std::fs::create_dir_all(out_dir).map_err(|e| {
            TypegenError::Io(format!(
                "failed to create output dir {}: {e}",
                out_dir.display()
            ))
        })?;

        let output = self.generate(schema)?;
        let mut written = Vec::new();

        if self.interfaces && !output.interfaces.is_empty() {
            let path = out_dir.join("models.ts");
            std::fs::write(&path, &output.interfaces).map_err(|e| {
                TypegenError::Io(format!("failed to write {}: {e}", path.display()))
            })?;
            written.push(path.display().to_string());
        }

        if self.zod && !output.zod.is_empty() {
            let path = out_dir.join("schemas.ts");
            std::fs::write(&path, &output.zod).map_err(|e| {
                TypegenError::Io(format!("failed to write {}: {e}", path.display()))
            })?;
            written.push(path.display().to_string());
        }

        if self.interfaces || self.zod {
            let index = build_index(self.interfaces, self.zod);
            let path = out_dir.join("index.ts");
            std::fs::write(&path, index).map_err(|e| {
                TypegenError::Io(format!("failed to write {}: {e}", path.display()))
            })?;
            written.push(path.display().to_string());
        }

        Ok(written)
    }
}

/// Generated TypeScript output.
#[derive(Debug, Default)]
pub struct GeneratedOutput {
    /// TypeScript interfaces.
    pub interfaces: String,
    /// Zod schemas.
    pub zod: String,
}

fn build_index(interfaces: bool, zod: bool) -> String {
    let mut lines = vec![
        "// Auto-generated by prax-typegen. Do not edit.".to_string(),
        String::new(),
    ];
    if interfaces {
        lines.push("export * from './models';".to_string());
    }
    if zod {
        lines.push("export * from './schemas';".to_string());
    }
    lines.push(String::new());
    lines.join("\n")
}

/// Check the schema for a generator named `name` and return whether it's enabled.
pub fn generator_enabled(schema: &Schema, name: &str) -> bool {
    schema.get_generator(name).is_some_and(|g| g.is_enabled())
}

/// Resolve the output directory from the generator block, falling back to a default.
pub fn resolve_output_dir(schema: &Schema, generator_name: &str, fallback: &str) -> String {
    schema
        .get_generator(generator_name)
        .and_then(|g| g.output.as_ref())
        .map(|s| s.to_string())
        .unwrap_or_else(|| fallback.to_string())
}
